service-url:
  credit-score: http://localhost:8081/api/v1/credit/score/{id}
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    continue-on-error: true
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    sshow-sql: true
